# Generated by Django 5.0.4 on 2024-04-04 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("amount", models.IntegerField(null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Groceries", "Groceries"),
                            ("Transportation", "Transportation"),
                            ("Utilities", "Utilities"),
                            ("Fixed expenses", "Fixed expenses"),
                            ("Savings contributions", "Savings contributions"),
                            ("Shopping", "Shopping"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(null=True)),
                ("merchant", models.CharField(max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Education", "Education"),
                            ("Groceries", "Groceries"),
                            ("Transportation", "Transportation"),
                            ("Utilities", "Utilities"),
                            ("Fixed expenses", "Fixed expenses"),
                            ("Shopping", "Shopping"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Credit card", "Credit card"),
                            ("Debit card", "Debit card"),
                            ("Bank transfer", "Bank transfer"),
                            ("Mobile money", "Mobile money"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
